name: Driver build
on: [push]
jobs:
  linux-amd64:
    name: Build Linux amd64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-amd64-${{ hashFiles('dirver/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-amd64-

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Build + install binaries
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --manifest-path driver/Cargo.toml

      - run: |
          mv driver/target/release/mirror-recipes-driver ./mirror-recipes-driver-linux-amd64

      - name: Upload to releases
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./mirror-recipes-driver-linux-amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#  linux-armv7hf:
#    name: Build Linux armv7hf
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout sources
#        uses: actions/checkout@v2
#
#      - uses: actions/cache@v2
#        with:
#          path: |
#            ~/.cargo/registry
#            ~/.cargo/git
#            target
#          key: ${{ runner.os }}-cargo-armv7hf-${{ hashFiles('dirver/Cargo.lock') }}
#          restore-keys: |
#            ${{ runner.os }}-cargo-armv7hf-
#
#      - name: Setup GCC
#        run: |
#          sudo apt update
#          sudo apt install gcc-arm-linux-gnueabihf
#
#      - uses: actions-rs/toolchain@v1
#        with:
#          toolchain: stable
#          target: armv7-unknown-linux-gnueabihf
#          override: true
#
#      - name: Build + install binaries
#        uses: actions-rs/cargo@v1
#        with:
#          use-cross: true
#          command: build
#          args: --release --target armv7-unknown-linux-gnueabihf --manifest-path driver/Cargo.toml
#
#      - run: |
#          mv driver/target/armv7-unknown-linux-gnueabihf/release/mirror-recipes-driver ./mirror-recipes-driver-linux-armv7hf
#
#      - name: Upload to releases
#        uses: softprops/action-gh-release@v1
#        if: startsWith(github.ref, 'refs/tags/')
#        with:
#          files: |
#            ./mirror-recipes-driver-linux-armv7hf
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#
