name: GitHub Pages deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Build
        run: |
          build/package.sh
          build/web.sh

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: output
